# Site wide configuration

encoding: utf-8
baseurl: http://blog.iken.be/en
url: http://blog.iken.be/en
title: Dancing Elephant
name: Ken Leung

# Jekyll configuration
permalink:   /:categories/:title/
markdown: redcarpet
sass:
  sass_dir: _sass
  style: compressed
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]


# Site owner
owner:
  name: Ken Leung
  avatar: bio-photo.jpg
  bio: "Describe your self."
  email: ikenbe@gmail.com
  disqus-shortname: ikenbe
  twitter: ikenbe
  facebook: iKen.Leung
  google:
    plus: iKenLeung
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: ikenbe
  stackoverflow:
  linkedin:
  instagram: ikenbe
  lastfm:
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: iken
  flickr: #username
